### PR TITLE
Add support for `RemoteEndpoint` in transport/client.

### PR DESCRIPTION
**Pull request by dengliming**
for [https://github.com/openzipkin/zipkin-go/issues/108](https://github.com/openzipkin/zipkin-go/issues/108)

@jcchavezs Can you help to review these changes?

### CODE REVIEW

**Comment by jcchavezs** [comment]
While my hunch is that in 97% of the cases this will only be used for
passing the service name, I think it is also good to keep consistency with
the local endpoint and also to keep the API surface tick by accepting the
Endpoint instead of just the service name (plus the endpoint as we should
also accept that too if we go for service name first).

Any thoughts @basvanbeek?

tir. 11. aug. 2020, 17:57 skrev Coveralls <notifications@github.com>:

**Comment by basvanbeek** [comment]
Agree with @jcchavezs. We should allow for remote endpoint as functional option instead of only the service name.

**Comment by dengliming** [comment]
@jcchavezs Hey~ just make sure I understand exactly what you mean. Do you mean like that?
```
type Client struct {
	*http.Client
	tracer            *zipkin.Tracer
	httpTrace         bool
	defaultTags       map[string]string
	transportOptions  []TransportOption
	remoteEndpoint *model.Endpoint
}

func WithRemoteEndpoint(remoteEndpoint *model.Endpoint) ClientOption {
	return func(c *Client) {
		c.remoteEndpoint = remoteEndpoint
	}
}
```

**Comment by jcchavezs** [comment]
Yes, exactly that.

ons. 12. aug. 2020, 15:38 skrev dengliming <notifications@github.com>:

**Comment by dengliming** [comment]
@jcchavezs Can you review again? Thanks.

**Comment by jcchavezs** [comment]
Thanks a lot!

**Pull request merged**
