### PR TITLE
chore: adds support for end time in spanImpl.

### PR DESCRIPTION
**Pull request by jcchavezs**
This PR adds a methods for finishing the span at a certain time. i have doubts about calling it `FinishAt` or `FinishedAt` (because you might pass a past time under general situations).

Ping @basvanbeek @stakhiv

### CODE REVIEW

**Comment by adriancole** [comment]
seems far more reasonable to use a precomputed duration. I'm gonna guess
this is opentracing huh? considering they plan to merge with census and
freeze their old api might consider finding another way to accomplish the
goal.

for example, if you can control the clock, in an OT wrapper you could
freeze time forward, then call finish normally.

talking out loud

**Comment by jcchavezs** [comment]
Well, this change is in an internal type so if the change in the API
happens we just need to remove this and let people deal with the vendoring.
Agree that a precomputed duration is way better.

Den tor. 28. feb. 2019, 00:55 skrev Adrian Cole <notifications@github.com>:

**Comment by basvanbeek** [comment]
I actually like the idea of precomputed duration. We could also make that a first class citizen to the Zipkin Go API and then for the OpenTracing wrapper basically calculate duration from Finish-Start.

**Comment by jcchavezs** [comment]
Makes sense. @stakhiv, would you mind to change it?

tor. 9. mai 2019, 19:46 skrev Bas van Beek <notifications@github.com>:

**Comment by jcchavezs** [comment]
Done @basvanbeek, would you mind to check the PR?

**Pull request merged**
