### PR TITLE
feat(#128): adds support for request sampler in client.

### PR DESCRIPTION
**Pull request by jcchavezs**
This PR adds support for request sampler in the Transport. Notice it has preference over existing sampling decision in the context.

Ping @basvanbeek

### CODE REVIEW

**Comment by basvanbeek** [comment]
This implementation forces a sampling decision if a request sampler is set.

I typically see the request sampler in a black/white list scenario. E.g.:
- must sample for /very/interesting/path
- must drop for /some/health/check

In this scenario we probably want to pass through the original sampling decision if we don't match the black/white lists.

We have two options:
1. have the user provide a request sampler that reads the current span decision and return that if there is no list match (this scenario has been implemented by me in the tests)
2. change the request sampler return value to `*bool` where nil means do not tamper with the existing context. (so the main tracer sampler's decision is passed through)

@adriancole @jcchavezs WDYT?

**Comment by jcchavezs** [comment]
Tricky one. Is override the decision to nil so downstream decides a real
use case? If it is then the nil return will not work for that. Maybe the
request sampler can receive the sampling decision and return the same?
Something like func(request, isSampled *bool) *bool that would be easier
for user instead of asking them to return the samplingFromContext. I also
think the fact that we pass the request (that already holds the sampling
decision) and the sampling decision is weird.

What if the request sampler received the request, the spanContext and
returns a new spanContext? Would that work or will be a source of errors if
people modify something else than the sampling decision?

tir. 9. jul. 2019, 19:38 skrev Bas van Beek <notifications@github.com>:

**Comment by basvanbeek** [comment]
So looking closer and taking into account the ability of having a noop tracer instance I think we really should go for the tribool implementation where we return the following:

- true: set sampling decision to yes, regardless of existing span context
- false: set sampling decision to no, regardless of existing span context
- nil: do not change anything, context remains untampered with by the RequestSampler

**Comment by jcchavezs** [comment]
Makes sense to me. Want to do the change @basvanbeek, otherwise I can do it later. Do we then still need the `SampledFromContext` function in that case?

In other questions, what about forcing all merges to be `Squash`?

**Comment by basvanbeek** [comment]
We don't need the SampledFromContext and I'd rather remove it... you can adjust to new tribool and then squash the commits to a single one up for review...

**Pull request merged**
