### PR TITLE
disallow pre unix epoch timestamps, allow negative duration

### PR DESCRIPTION
**Pull request by basvanbeek**
Improves Timestamp and Duration handling

### CODE REVIEW

**Comment by adriancole** [comment]
I dont quite get why we explicitly allow negative duration for
troubleshooting. Duration is minimum 1us when present in other tracers as
even 0 has caused confusion. Whats the story here?

**Comment by basvanbeek** [comment]
not much except for adding extra handling in model. tracer implementation would not allow this to happen anyway... only remaining question is... do we fail the span to json serialization or remove the offending Duration?

**Comment by adriancole** [comment]
Judgement call I guess. 0 can be an accident of empty. Negative is invalid,
but I bet it ends up stored (due to no strict checks).

**Comment by jcchavezs** [comment]
@basvanbeek @adriancole does it make sense to change the spec?

```
timestamp | integer($int64) -> timestamp | integer($uint64)
duration | integer($int64) -> duration | integer($int64)
```

**Comment by adriancole** [comment]
If swagger supports that, yeah. Though uint64 wont fit in json ;) wanna try?

**Pull request closed without merging**
