### PR TITLE
Add exponential backoff logic to Zipkin http reporter

### LINKED ISSUE #153: Add exponential backoff logic to http reporter on failure to send data to the backend
Zipkin http reporter should backoff when sending data to the backend fails to reduce the number of failed retries when the backend is down (once per second by default atm).

See #147 for previous discussion.

cc @basvanbeek @adriancole @jcchavezs @pramodramdas

### PR DESCRIPTION
**Pull request by skaslev**
Implement backoff logic for the http reporter when sending data to the
backend fails or the backend is down.

Fixes #153

### CODE REVIEW

**Comment by jcchavezs** [comment]
Looks good. I have a question, should we bound the number of retries? Something like in https://github.com/openzipkin/zipkin-go/pull/151/files#diff-b0da46b1429d81a3b375df746afe34f9R58 where after a number of retries we just drop the spans? cc @basvanbeek @adriancole

**Comment by jcchavezs** [comment]
Giving it a second thought. I think this is more complex than we could expect. Maybe the best approach is the simplest: retry a few times and then discard traces.

**Comment by skaslev** [comment]
One advantage of this approach is that if there's a backend hiccup (backend goes down but get restarted and becomes operational after awhile), the system will recover eventually and continue to send tracing data. While the approach taken in #151 (which I missed to see before sending this) will give up after `MaxRetries`.

On the complexity side, I'm open to suggestions how to make it simpler. The code is based on the gRPC's internal [exponential backoff algorithm](https://github.com/grpc/grpc-go/blob/7c8e60372e19da88fb3fe8ac6a8de781eef7f547/internal/backoff/backoff.go#L54) licensed as Apache License, Version 2.0.

**Comment by adriancole** [comment]
My main request is if there isn't a library that could be used that has resilience mechanics built-in, then users pass that library. this seems like commodity HTTP retry stuff which makes it feel odd we should host and maintain that.

That said, I'm not involved in either golang or in this codebase, this is just a question to ponder.

**Comment by basvanbeek** [comment]
A possible library we could use: https://github.com/hashicorp/go-retryablehttp

**Comment by skaslev** [comment]
> A possible library we could use: https://github.com/hashicorp/go-retryablehttp

Sounds good. I'll give it a try and send another PR for review.

**Comment by skaslev** [comment]
Closing this since discussion moved to #155

**Pull request closed without merging**
